// Query TypeMap
import '@sanity/client'

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Work = {
  _id: string
  _type: 'work'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageAlt?: string
  introTitle?: string
  introDescription?: string
  ctaTitle?: string
  ctaDescription?: string
  ctaHref?: string
  ctaButtonText?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Contact = {
  _id: string
  _type: 'contact'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageAlt?: string
  email?: string
  contactFormEmail?: string
  phone?: string
  address?: {
    street?: string
    city?: string
    postalCode?: string
  }
  socialLinks?: {
    instagram?: string
    facebook?: string
    linkedin?: string
    pinterest?: string
  }
  formTitle?: string
  formDescription?: string
  ctaHref?: string
  ctaButtonText?: string
}

export type About = {
  _id: string
  _type: 'about'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  team?: Array<{
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    imageAlt?: string
    name?: string
    role?: string
    bio?: string
    quote?: string
    specializations?: Array<string>
    email?: string
    phone?: string
    instagram?: string
    _type: 'teamMember'
    _key: string
  }>
  ctaTitle?: string
  ctaDescription?: string
  ctaHref?: string
  ctaButtonText?: string
}

export type Portfolio = {
  _id: string
  _type: 'portfolio'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  projects?: Array<{
    images?: Array<{
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }>
    title?: string
    category?: string
    location?: string
    area?: number
    year?: number
    description?: string
    _key: string
  }>
}

export type Offer = {
  _id: string
  _type: 'offer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  services?: Array<{
    title?: string
    description?: string
    note?: string
    variants?: Array<{
      image?: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      imageAlt?: string
      badge?: string
      name?: string
      isRecommended?: boolean
      items?: Array<string>
      note?: string
      _key: string
    }>
    _key: string
  }>
  ctaTitle?: string
  ctaDescription?: string
  ctaHref?: string
  ctaButtonText?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  footer?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  logoImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  imagesCarousel?: Array<{
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    imageAlt?: string
    title?: string
    description?: string
    hoverText?: string
    link?: string
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Work
  | SanityImageCrop
  | SanityImageHotspot
  | Contact
  | About
  | Portfolio
  | Offer
  | Settings
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "home"][0]{    _id,    _type,    imagesCarousel[]{      _key,      _id,      _type,      image{        ...,        asset->{          ...,          metadata{            lqip          }        }      },      imageAlt,      title,      description,      link,      hoverText    },    title,    description  }
export type HomePageQueryResult = {
  _id: string
  _type: 'home'
  imagesCarousel: Array<{
    _key: string
    _id: null
    _type: null
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata: {
          lqip: string | null
        } | null
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    imageAlt: string | null
    title: string | null
    description: string | null
    link: string | null
    hoverText: string | null
  }> | null
  title: string | null
  description: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{    _id,    _type,    footer,    logoImage{      ...,      asset->{        ...,        metadata{          lqip        }      }    },  }
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  footer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  logoImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata: {
        lqip: string | null
      } | null
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: offerPageQuery
// Query: *[_type == "offer"][0]{    _id,    _type,    title,    description,    services[]{      _key,      title,      description,      note,      variants[]{        _key,        image{          ...,          asset->{            ...,            metadata{              lqip            }          }        },        imageAlt,        badge,        name,        isRecommended,        items,        note      }    },    ctaTitle,    ctaDescription,    ctaHref,    ctaButtonText  }
export type OfferPageQueryResult = {
  _id: string
  _type: 'offer'
  title: string | null
  description: string | null
  services: Array<{
    _key: string
    title: string | null
    description: string | null
    note: string | null
    variants: Array<{
      _key: string
      image: {
        asset: {
          _id: string
          _type: 'sanity.imageAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash?: string
          extension?: string
          mimeType?: string
          size?: number
          assetId?: string
          uploadId?: string
          path?: string
          url?: string
          metadata: {
            lqip: string | null
          } | null
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      } | null
      imageAlt: string | null
      badge: string | null
      name: string | null
      isRecommended: boolean | null
      items: Array<string> | null
      note: string | null
    }> | null
  }> | null
  ctaTitle: string | null
  ctaDescription: string | null
  ctaHref: string | null
  ctaButtonText: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "about"][0]{    _id,    _type,    title,    description,    team[]{      _key,      image{        ...,        asset->{          ...,          metadata{            lqip          }        }      },      imageAlt,      name,      role,      bio,      quote,      specializations,      email,      phone,      instagram    },    ctaTitle,    ctaDescription,    ctaHref,    ctaButtonText  }
export type AboutPageQueryResult = {
  _id: string
  _type: 'about'
  title: string | null
  description: string | null
  team: Array<{
    _key: string
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash?: string
        extension?: string
        mimeType?: string
        size?: number
        assetId?: string
        uploadId?: string
        path?: string
        url?: string
        metadata: {
          lqip: string | null
        } | null
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    imageAlt: string | null
    name: string | null
    role: string | null
    bio: string | null
    quote: string | null
    specializations: Array<string> | null
    email: string | null
    phone: string | null
    instagram: string | null
  }> | null
  ctaTitle: string | null
  ctaDescription: string | null
  ctaHref: string | null
  ctaButtonText: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contact"][0]{    _id,    _type,    title,    description,    image{      ...,      asset->{        ...,        metadata{          lqip        }      }    },    imageAlt,    email,    contactFormEmail,    phone,    address{      street,      city,      postalCode    },    socialLinks{      instagram,      facebook,      linkedin,      pinterest    },    formTitle,    formDescription,    ctaHref,    ctaButtonText  }
export type ContactPageQueryResult = {
  _id: string
  _type: 'contact'
  title: string | null
  description: string | null
  image: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata: {
        lqip: string | null
      } | null
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  imageAlt: string | null
  email: string | null
  contactFormEmail: string | null
  phone: string | null
  address: {
    street: string | null
    city: string | null
    postalCode: string | null
  } | null
  socialLinks: {
    instagram: string | null
    facebook: string | null
    linkedin: string | null
    pinterest: string | null
  } | null
  formTitle: string | null
  formDescription: string | null
  ctaHref: string | null
  ctaButtonText: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: workPageQuery
// Query: *[_type == "work"][0]{    _id,    _type,    title,    description,    image{      ...,      asset->{        ...,        metadata{          lqip        }      }    },    imageAlt,    introTitle,    introDescription,    ctaTitle,    ctaDescription,    ctaHref,    ctaButtonText  }
export type WorkPageQueryResult = {
  _id: string
  _type: 'work'
  title: string | null
  description: string | null
  image: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash?: string
      extension?: string
      mimeType?: string
      size?: number
      assetId?: string
      uploadId?: string
      path?: string
      url?: string
      metadata: {
        lqip: string | null
      } | null
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  imageAlt: string | null
  introTitle: string | null
  introDescription: string | null
  ctaTitle: string | null
  ctaDescription: string | null
  ctaHref: string | null
  ctaButtonText: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: slugsByTypeQuery
// Query: *[_type == $type && defined(slug.current)]{"slug": slug.current}
export type SlugsByTypeQueryResult = Array<never>

declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    _type,\n    imagesCarousel[]{\n      _key,\n      _id,\n      _type,\n      image{\n        ...,\n        asset->{\n          ...,\n          metadata{\n            lqip\n          }\n        }\n      },\n      imageAlt,\n      title,\n      description,\n      link,\n      hoverText\n    },\n    title,\n    description\n  }\n': HomePageQueryResult
    '\n  *[_type == "settings"][0]{\n    _id,\n    _type,\n    footer,\n    logoImage{\n      ...,\n      asset->{\n        ...,\n        metadata{\n          lqip\n        }\n      }\n    },\n  }\n': SettingsQueryResult
    '\n  *[_type == "offer"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    services[]{\n      _key,\n      title,\n      description,\n      note,\n      variants[]{\n        _key,\n        image{\n          ...,\n          asset->{\n            ...,\n            metadata{\n              lqip\n            }\n          }\n        },\n        imageAlt,\n        badge,\n        name,\n        isRecommended,\n        items,\n        note\n      }\n    },\n    ctaTitle,\n    ctaDescription,\n    ctaHref,\n    ctaButtonText\n  }\n': OfferPageQueryResult
    '\n  *[_type == "about"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    team[]{\n      _key,\n      image{\n        ...,\n        asset->{\n          ...,\n          metadata{\n            lqip\n          }\n        }\n      },\n      imageAlt,\n      name,\n      role,\n      bio,\n      quote,\n      specializations,\n      email,\n      phone,\n      instagram\n    },\n    ctaTitle,\n    ctaDescription,\n    ctaHref,\n    ctaButtonText\n  }\n': AboutPageQueryResult
    '\n  *[_type == "contact"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    image{\n      ...,\n      asset->{\n        ...,\n        metadata{\n          lqip\n        }\n      }\n    },\n    imageAlt,\n    email,\n    contactFormEmail,\n    phone,\n    address{\n      street,\n      city,\n      postalCode\n    },\n    socialLinks{\n      instagram,\n      facebook,\n      linkedin,\n      pinterest\n    },\n    formTitle,\n    formDescription,\n    ctaHref,\n    ctaButtonText\n  }\n': ContactPageQueryResult
    '\n  *[_type == "work"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    image{\n      ...,\n      asset->{\n        ...,\n        metadata{\n          lqip\n        }\n      }\n    },\n    imageAlt,\n    introTitle,\n    introDescription,\n    ctaTitle,\n    ctaDescription,\n    ctaHref,\n    ctaButtonText\n  }\n': WorkPageQueryResult
    '\n  *[_type == $type && defined(slug.current)]{"slug": slug.current}\n': SlugsByTypeQueryResult
  }
}
