// Query TypeMap
import '@sanity/client'

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Work = {
  _id: string
  _type: 'work'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  intro?: string
  perks?: Array<{
    icon?: string
    title?: string
    description?: string
    _key: string
  }>
  openPositions?: Array<{
    position?: string
    type?: 'uop' | 'b2b' | 'zlecenie' | 'staz'
    experience?: 'junior' | 'mid' | 'senior'
    description?: string
    requirements?: Array<string>
    isActive?: boolean
    _key: string
  }>
  spontaneousApplication?: {
    title?: string
    description?: string
    email?: string
  }
}

export type Contact = {
  _id: string
  _type: 'contact'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  email?: string
  phone?: string
  address?: {
    street?: string
    city?: string
    postalCode?: string
  }
  socialLinks?: {
    instagram?: string
    facebook?: string
    linkedin?: string
    pinterest?: string
  }
  formTitle?: string
  formDescription?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Portfolio = {
  _id: string
  _type: 'portfolio'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  projects?: Array<{
    images?: Array<{
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }>
    title?: string
    category?: string
    location?: string
    area?: number
    year?: number
    description?: string
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Offer = {
  _id: string
  _type: 'offer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  services?: Array<{
    icon?: string
    title?: string
    description?: string
    scope?: Array<string>
    _key: string
  }>
  process?: Array<{
    step?: number
    title?: string
    description?: string
    _key: string
  }>
  ctaTitle?: string
  ctaDescription?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  footer?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  logoImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  imagesCarousel?: Array<{
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    title?: string
    description?: string
    hoverText?: string
    link?: string
    _key: string
  }>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | Work
  | Contact
  | SanityImageAssetReference
  | Portfolio
  | SanityImageCrop
  | SanityImageHotspot
  | Offer
  | Settings
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "home"][0]{    _id,    _type,    imagesCarousel[]{      _key,      _id,      _type,      image,      title,      description,      link,      hoverText    },    title,    description  }
export type HomePageQueryResult = {
  _id: string
  _type: 'home'
  imagesCarousel: Array<{
    _key: string
    _id: null
    _type: null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    title: string | null
    description: string | null
    link: string | null
    hoverText: string | null
  }> | null
  title: string | null
  description: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{    _id,    _type,    footer,    logoImage,  }
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  footer: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  logoImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: offerPageQuery
// Query: *[_type == "offer"][0]{    _id,    _type,    title,    description,    services[]{      _key,      icon,      title,      description,      scope    },    process[]{      _key,      step,      title,      description    },    ctaTitle,    ctaDescription  }
export type OfferPageQueryResult = {
  _id: string
  _type: 'offer'
  title: string | null
  description: string | null
  services: Array<{
    _key: string
    icon: string | null
    title: string | null
    description: string | null
    scope: Array<string> | null
  }> | null
  process: Array<{
    _key: string
    step: number | null
    title: string | null
    description: string | null
  }> | null
  ctaTitle: string | null
  ctaDescription: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: portfolioPageQuery
// Query: *[_type == "portfolio"][0]{    _id,    _type,    title,    description,    projects[]{      _key,      title,      category,      location,      area,      year,      description,      images[]{        _key,        asset->{          _id,          url,          metadata{            dimensions          }        },        hotspot,        crop      }    }  }
export type PortfolioPageQueryResult = {
  _id: string
  _type: 'portfolio'
  title: string | null
  description: string | null
  projects: Array<{
    _key: string
    title: string | null
    category: string | null
    location: string | null
    area: number | null
    year: number | null
    description: string | null
    images: Array<{
      _key: string
      asset: {
        _id: string
        url: string | null
        metadata: {
          dimensions: SanityImageDimensions | null
        } | null
      } | null
      hotspot: SanityImageHotspot | null
      crop: SanityImageCrop | null
    }> | null
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: contactPageQuery
// Query: *[_type == "contact"][0]{    _id,    _type,    title,    description,    email,    phone,    address{      street,      city,      postalCode    },    socialLinks{      instagram,      facebook,      linkedin,      pinterest    },    formTitle,    formDescription  }
export type ContactPageQueryResult = {
  _id: string
  _type: 'contact'
  title: string | null
  description: string | null
  email: string | null
  phone: string | null
  address: {
    street: string | null
    city: string | null
    postalCode: string | null
  } | null
  socialLinks: {
    instagram: string | null
    facebook: string | null
    linkedin: string | null
    pinterest: string | null
  } | null
  formTitle: string | null
  formDescription: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: workPageQuery
// Query: *[_type == "work"][0]{    _id,    _type,    title,    description,    intro,    perks[]{      _key,      icon,      title,      description    },    openPositions[]{      _key,      position,      type,      experience,      description,      requirements,      isActive    },    spontaneousApplication{      title,      description,      email    }  }
export type WorkPageQueryResult = {
  _id: string
  _type: 'work'
  title: string | null
  description: string | null
  intro: string | null
  perks: Array<{
    _key: string
    icon: string | null
    title: string | null
    description: string | null
  }> | null
  openPositions: Array<{
    _key: string
    position: string | null
    type: 'b2b' | 'staz' | 'uop' | 'zlecenie' | null
    experience: 'junior' | 'mid' | 'senior' | null
    description: string | null
    requirements: Array<string> | null
    isActive: boolean | null
  }> | null
  spontaneousApplication: {
    title: string | null
    description: string | null
    email: string | null
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: slugsByTypeQuery
// Query: *[_type == $type && defined(slug.current)]{"slug": slug.current}
export type SlugsByTypeQueryResult = Array<never>

declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    _type,\n    imagesCarousel[]{\n      _key,\n      _id,\n      _type,\n      image,\n      title,\n      description,\n      link,\n      hoverText\n    },\n    title,\n    description\n  }\n': HomePageQueryResult
    '\n  *[_type == "settings"][0]{\n    _id,\n    _type,\n    footer,\n    logoImage,\n  }\n': SettingsQueryResult
    '\n  *[_type == "offer"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    services[]{\n      _key,\n      icon,\n      title,\n      description,\n      scope\n    },\n    process[]{\n      _key,\n      step,\n      title,\n      description\n    },\n    ctaTitle,\n    ctaDescription\n  }\n': OfferPageQueryResult
    '\n  *[_type == "portfolio"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    projects[]{\n      _key,\n      title,\n      category,\n      location,\n      area,\n      year,\n      description,\n      images[]{\n        _key,\n        asset->{\n          _id,\n          url,\n          metadata{\n            dimensions\n          }\n        },\n        hotspot,\n        crop\n      }\n    }\n  }\n': PortfolioPageQueryResult
    '\n  *[_type == "contact"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    email,\n    phone,\n    address{\n      street,\n      city,\n      postalCode\n    },\n    socialLinks{\n      instagram,\n      facebook,\n      linkedin,\n      pinterest\n    },\n    formTitle,\n    formDescription\n  }\n': ContactPageQueryResult
    '\n  *[_type == "work"][0]{\n    _id,\n    _type,\n    title,\n    description,\n    intro,\n    perks[]{\n      _key,\n      icon,\n      title,\n      description\n    },\n    openPositions[]{\n      _key,\n      position,\n      type,\n      experience,\n      description,\n      requirements,\n      isActive\n    },\n    spontaneousApplication{\n      title,\n      description,\n      email\n    }\n  }\n': WorkPageQueryResult
    '\n  *[_type == $type && defined(slug.current)]{"slug": slug.current}\n': SlugsByTypeQueryResult
  }
}
